# Generated by Django 5.0.2 on 2024-02-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('P', 'Para adoção'), ('A', 'Adotado')], default='P', max_length=1),
        ),
    ]
